
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftBINARY_PLUSBINARY_UNARY_MINUSleftBINARY_MULTIPLYBINARY_DIVIDEASSIGN BINARY_DIVIDE BINARY_MULTIPLY BINARY_PLUS BINARY_UNARY_MINUS COMMA CONSTANT IDENTIFIER LEFT_BRACKET RIGHT_BRACKET SEMICOLON TYPEprogram : declaringvariables descriptionofcalculationsdeclaringvariables : TYPE listofvariables SEMICOLONlistofvariables : identifier COMMA listofvariables\n                       | identifieridentifier : IDENTIFIERdescriptionofcalculations : listofassignmentslistofassignments : assignment listofassignments\n                         | assignmentassignment : identifier ASSIGN expressionexpression : BINARY_UNARY_MINUS subexpression\n                  | subexpressionsubexpression : LEFT_BRACKET expression RIGHT_BRACKET\n                     | expression BINARY_PLUS expression\n                     | expression BINARY_UNARY_MINUS expression\n                     | expression BINARY_MULTIPLY expression\n                     | expression BINARY_DIVIDE expression\n                     | operandoperand : identifier\n               | constantconstant : CONSTANT'
    
_lr_action_items = {'TYPE':([0,],[3,]),'$end':([1,4,5,6,8,11,15,16,18,20,21,22,28,31,32,33,34,35,],[0,-1,-6,-8,-5,-7,-18,-9,-11,-17,-19,-20,-10,-13,-14,-15,-16,-12,]),'IDENTIFIER':([2,3,6,8,12,13,14,15,16,17,18,19,20,21,22,24,25,26,27,28,31,32,33,34,35,],[8,8,8,-5,8,-2,8,-18,-9,8,-11,8,-17,-19,-20,8,8,8,8,-10,-13,-14,-15,-16,-12,]),'ASSIGN':([7,8,],[12,-5,]),'COMMA':([8,10,],[-5,14,]),'SEMICOLON':([8,9,10,23,],[-5,13,-4,-3,]),'BINARY_PLUS':([8,15,16,18,20,21,22,28,29,30,31,32,33,34,35,],[-5,-18,24,-11,-17,-19,-20,-10,24,24,-13,-14,-15,-16,-12,]),'BINARY_UNARY_MINUS':([8,12,15,16,17,18,19,20,21,22,24,25,26,27,28,29,30,31,32,33,34,35,],[-5,17,-18,25,17,-11,17,-17,-19,-20,17,17,17,17,-10,25,25,-13,-14,-15,-16,-12,]),'BINARY_MULTIPLY':([8,15,16,18,20,21,22,28,29,30,31,32,33,34,35,],[-5,-18,26,-11,-17,-19,-20,-10,26,26,26,26,-15,-16,-12,]),'BINARY_DIVIDE':([8,15,16,18,20,21,22,28,29,30,31,32,33,34,35,],[-5,-18,27,-11,-17,-19,-20,-10,27,27,27,27,-15,-16,-12,]),'RIGHT_BRACKET':([8,15,18,20,21,22,28,30,31,32,33,34,35,],[-5,-18,-11,-17,-19,-20,-10,35,-13,-14,-15,-16,-12,]),'LEFT_BRACKET':([12,17,19,24,25,26,27,],[19,19,19,19,19,19,19,]),'CONSTANT':([12,17,19,24,25,26,27,],[22,22,22,22,22,22,22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'declaringvariables':([0,],[2,]),'descriptionofcalculations':([2,],[4,]),'listofassignments':([2,6,],[5,11,]),'assignment':([2,6,],[6,6,]),'identifier':([2,3,6,12,14,17,19,24,25,26,27,],[7,10,7,15,10,15,15,15,15,15,15,]),'listofvariables':([3,14,],[9,23,]),'expression':([12,17,19,24,25,26,27,],[16,29,30,31,32,33,34,]),'subexpression':([12,17,19,24,25,26,27,],[18,28,18,18,18,18,18,]),'operand':([12,17,19,24,25,26,27,],[20,20,20,20,20,20,20,]),'constant':([12,17,19,24,25,26,27,],[21,21,21,21,21,21,21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> declaringvariables descriptionofcalculations','program',2,'p_program','yacc.py',15),
  ('declaringvariables -> TYPE listofvariables SEMICOLON','declaringvariables',3,'p_declaringvariables','yacc.py',19),
  ('listofvariables -> identifier COMMA listofvariables','listofvariables',3,'p_listofvariables','yacc.py',23),
  ('listofvariables -> identifier','listofvariables',1,'p_listofvariables','yacc.py',24),
  ('identifier -> IDENTIFIER','identifier',1,'p_identifier','yacc.py',31),
  ('descriptionofcalculations -> listofassignments','descriptionofcalculations',1,'p_descriptionofcalculations','yacc.py',35),
  ('listofassignments -> assignment listofassignments','listofassignments',2,'p_listofassignments','yacc.py',39),
  ('listofassignments -> assignment','listofassignments',1,'p_listofassignments','yacc.py',40),
  ('assignment -> identifier ASSIGN expression','assignment',3,'p_assignment','yacc.py',47),
  ('expression -> BINARY_UNARY_MINUS subexpression','expression',2,'p_expression','yacc.py',51),
  ('expression -> subexpression','expression',1,'p_expression','yacc.py',52),
  ('subexpression -> LEFT_BRACKET expression RIGHT_BRACKET','subexpression',3,'p_subexpression','yacc.py',59),
  ('subexpression -> expression BINARY_PLUS expression','subexpression',3,'p_subexpression','yacc.py',60),
  ('subexpression -> expression BINARY_UNARY_MINUS expression','subexpression',3,'p_subexpression','yacc.py',61),
  ('subexpression -> expression BINARY_MULTIPLY expression','subexpression',3,'p_subexpression','yacc.py',62),
  ('subexpression -> expression BINARY_DIVIDE expression','subexpression',3,'p_subexpression','yacc.py',63),
  ('subexpression -> operand','subexpression',1,'p_subexpression','yacc.py',64),
  ('operand -> identifier','operand',1,'p_operand','yacc.py',80),
  ('operand -> constant','operand',1,'p_operand','yacc.py',81),
  ('constant -> CONSTANT','constant',1,'p_constant','yacc.py',85),
]
